
# This file is automatically generated, you probably don't want to edit this

correlationsOptions <- if (requireNamespace("jmvcore", quietly=TRUE)) R6::R6Class(
    "correlationsOptions",
    inherit = jmvcore::Options,
    public = list(
        initialize = function(
            vars = NULL,
            group = NULL,
            flag = FALSE, ...) {

            super$initialize(
                package="ESMhelpers",
                name="correlations",
                requiresData=TRUE,
                ...)

            private$..vars <- jmvcore::OptionVariables$new(
                "vars",
                vars,
                suggested=list(
                    "continuous"))
            private$..group <- jmvcore::OptionVariable$new(
                "group",
                group,
                suggested=list(
                    "nominal"))
            private$..flag <- jmvcore::OptionBool$new(
                "flag",
                flag,
                default=FALSE)

            self$.addOption(private$..vars)
            self$.addOption(private$..group)
            self$.addOption(private$..flag)
        }),
    active = list(
        vars = function() private$..vars$value,
        group = function() private$..group$value,
        flag = function() private$..flag$value),
    private = list(
        ..vars = NA,
        ..group = NA,
        ..flag = NA)
)

correlationsResults <- if (requireNamespace("jmvcore", quietly=TRUE)) R6::R6Class(
    "correlationsResults",
    inherit = jmvcore::Group,
    active = list(
        text = function() private$.items[["text"]],
        matrixbg = function() private$.items[["matrixbg"]],
        matrixwg = function() private$.items[["matrixwg"]]),
    private = list(),
    public=list(
        initialize=function(options) {
            super$initialize(
                options=options,
                name="",
                title="Correlation Matrix")
            self$add(jmvcore::Preformatted$new(
                options=options,
                name="text",
                title="Correlation Matrix"))
            self$add(jmvcore::Table$new(
                options=options,
                name="matrixbg",
                title="Correlation Matrix - Between Groups",
                rows="(vars)",
                clearWith=list(
                    "flag"),
                columns=list(
                    list(
                        `name`=".name[r]", 
                        `title`="", 
                        `type`="text", 
                        `content`="($key)", 
                        `combineBelow`=TRUE, 
                        `visible`=TRUE))))
            self$add(jmvcore::Table$new(
                options=options,
                name="matrixwg",
                title="Correlation Matrix - Within Groups",
                rows="(vars)",
                clearWith=list(
                    "flag"),
                columns=list(
                    list(
                        `name`=".name[r]", 
                        `title`="", 
                        `type`="text", 
                        `content`="($key)", 
                        `combineBelow`=TRUE, 
                        `visible`=TRUE))))}))

correlationsBase <- if (requireNamespace("jmvcore", quietly=TRUE)) R6::R6Class(
    "correlationsBase",
    inherit = jmvcore::Analysis,
    public = list(
        initialize = function(options, data=NULL, datasetId="", analysisId="", revision=0) {
            super$initialize(
                package = "ESMhelpers",
                name = "correlations",
                version = c(1,0,0),
                options = options,
                results = correlationsResults$new(options=options),
                data = data,
                datasetId = datasetId,
                analysisId = analysisId,
                revision = revision,
                pause = NULL,
                completeWhenFilled = FALSE,
                requiresMissings = FALSE,
                weightsSupport = 'auto')
        }))

#' Correlation Matrix
#'
#' 
#' @param data .
#' @param vars .
#' @param group .
#' @param flag .
#' @return A results object containing:
#' \tabular{llllll}{
#'   \code{results$text} \tab \tab \tab \tab \tab a preformatted \cr
#'   \code{results$matrixbg} \tab \tab \tab \tab \tab a correlation matrix table \cr
#'   \code{results$matrixwg} \tab \tab \tab \tab \tab a correlation matrix table \cr
#' }
#'
#' Tables can be converted to data frames with \code{asDF} or \code{\link{as.data.frame}}. For example:
#'
#' \code{results$matrixbg$asDF}
#'
#' \code{as.data.frame(results$matrixbg)}
#'
#' @export
correlations <- function(
    data,
    vars,
    group,
    flag = FALSE) {

    if ( ! requireNamespace("jmvcore", quietly=TRUE))
        stop("correlations requires jmvcore to be installed (restart may be required)")

    if ( ! missing(vars)) vars <- jmvcore::resolveQuo(jmvcore::enquo(vars))
    if ( ! missing(group)) group <- jmvcore::resolveQuo(jmvcore::enquo(group))
    if (missing(data))
        data <- jmvcore::marshalData(
            parent.frame(),
            `if`( ! missing(vars), vars, NULL),
            `if`( ! missing(group), group, NULL))


    options <- correlationsOptions$new(
        vars = vars,
        group = group,
        flag = flag)

    analysis <- correlationsClass$new(
        options = options,
        data = data)

    analysis$run()

    analysis$results
}

