
# This file is automatically generated, you probably don't want to edit this

omegaOptions <- if (requireNamespace("jmvcore", quietly=TRUE)) R6::R6Class(
    "omegaOptions",
    inherit = jmvcore::Options,
    public = list(
        initialize = function(
            items = NULL,
            group = NULL, ...) {

            super$initialize(
                package="ESMhelpers",
                name="omega",
                requiresData=TRUE,
                ...)

            private$..items <- jmvcore::OptionVariables$new(
                "items",
                items,
                suggested=list(
                    "continuous"))
            private$..group <- jmvcore::OptionVariable$new(
                "group",
                group,
                suggested=list(
                    "nominal"))

            self$.addOption(private$..items)
            self$.addOption(private$..group)
        }),
    active = list(
        items = function() private$..items$value,
        group = function() private$..group$value),
    private = list(
        ..items = NA,
        ..group = NA)
)

omegaResults <- if (requireNamespace("jmvcore", quietly=TRUE)) R6::R6Class(
    "omegaResults",
    inherit = jmvcore::Group,
    active = list(
        text = function() private$.items[["text"]]),
    private = list(),
    public=list(
        initialize=function(options) {
            super$initialize(
                options=options,
                name="",
                title="Multilevel Reliability with Omega")
            self$add(jmvcore::Preformatted$new(
                options=options,
                name="text",
                title="Multilevel Reliability with Omega"))}))

omegaBase <- if (requireNamespace("jmvcore", quietly=TRUE)) R6::R6Class(
    "omegaBase",
    inherit = jmvcore::Analysis,
    public = list(
        initialize = function(options, data=NULL, datasetId="", analysisId="", revision=0) {
            super$initialize(
                package = "ESMhelpers",
                name = "omega",
                version = c(1,0,0),
                options = options,
                results = omegaResults$new(options=options),
                data = data,
                datasetId = datasetId,
                analysisId = analysisId,
                revision = revision,
                pause = NULL,
                completeWhenFilled = FALSE,
                requiresMissings = FALSE,
                weightsSupport = 'auto')
        }))

#' Multilevel Reliability with Omega
#'
#' 
#' @param data .
#' @param items .
#' @param group .
#' @return A results object containing:
#' \tabular{llllll}{
#'   \code{results$text} \tab \tab \tab \tab \tab a preformatted \cr
#' }
#'
#' @export
omega <- function(
    data,
    items,
    group) {

    if ( ! requireNamespace("jmvcore", quietly=TRUE))
        stop("omega requires jmvcore to be installed (restart may be required)")

    if ( ! missing(items)) items <- jmvcore::resolveQuo(jmvcore::enquo(items))
    if ( ! missing(group)) group <- jmvcore::resolveQuo(jmvcore::enquo(group))
    if (missing(data))
        data <- jmvcore::marshalData(
            parent.frame(),
            `if`( ! missing(items), items, NULL),
            `if`( ! missing(group), group, NULL))


    options <- omegaOptions$new(
        items = items,
        group = group)

    analysis <- omegaClass$new(
        options = options,
        data = data)

    analysis$run()

    analysis$results
}

